<?php

namespace PacksAnSpielBundle\Repository;

use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\Query\ResultSetMapping;
use PacksAnSpielBundle\Entity\Word;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOneRandom()
    {
        $rsm = new ResultSetMapping();
        $rsm->addEntityResult('PacksAnSpielBundle:Word', 'r1');
        $rsm->addEntityResult('PacksAnSpielBundle:Word', 'r2');
        $rsm->addEntityResult('PacksAnSpielBundle:Word', 'r3');
        $rsm->addFieldResult('r1', 'name', 'name');
        $rsm->addFieldResult('r1', 'id', 'id');

        $queryString = "SELECT r1.id, r1.name 
                FROM word r1 
                JOIN (SELECT CEIL(RAND() * (SELECT MAX(r3.id) FROM word r3)) AS id) r2 
                WHERE r1.id >= r2.id 
                ORDER BY r1.id ASC LIMIT 1 OFFSET 0";
        $query = $this->_em->createNativeQuery($queryString, $rsm);
        $word = $query->getOneOrNullResult();

        return $word;


    }
}
