# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  packsan.user.provider.class: PacksAnSpielBundle\Repository\TeamRepository
  packsan.user.provider.entity.class: PacksAnSpielBundle\Entity\Team

services:
  packsan.user.provider:
    class: %packsan.user.provider.class%
    factory_service: doctrine
    factory_method: getRepository
    arguments:
      - %packsan.user.provider.entity.class%