# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  packsan.user.provider.class: PacksAnSpielBundle\Repository\TeamRepository
  packsan.user.provider.entity.class: PacksAnSpielBundle\Entity\Team
  packsan.game.logic.class: PacksAnSpielBundle\Game\GameLogic
  packsan.game.logger.class: PacksAnSpielBundle\Game\GameActionLogger
  packsan_admin.menu_listener.class: PacksAnSpielBundle\EventListener\AdminMenuItemListListener

services:
#  packsan.user.provider:
#    class: %packsan.user.provider.class%
#    factory_service: doctrine
#    factory_method: getRepository
#    arguments:
#      - %packsan.user.provider.entity.class%

  packsan.game.logic:
    class:        %packsan.game.logic.class%
    arguments:     [ "@doctrine.orm.entity_manager" ]

  packsan.action.logger:
    class:        %packsan.game.logger.class%
    arguments:     [ "@doctrine.orm.entity_manager" ]

  packsan_admin.menu_listener:
            class: %packsan_admin.menu_listener.class%
            tags:
                - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }