PacksAnSpielBundle\Entity\Actionlog:
    type: entity
    table: actionlog
    indexes:
        fk_actionlog_team1_idx:
            columns:
                - team_id
        fk_actionlog_game1_idx:
            columns:
                - game_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
    fields:
        logText:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: log_text
        timestamp:
            type: time
            nullable: true
    oneToOne:
        game:
            targetEntity: Game
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                game_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToOne:
        team:
            targetEntity: Team
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
