PacksAnSpielBundle\Entity\GameSubject:
    type: entity
    repositoryClass: PacksAnSpielBundle\Repository\GameSubjectRepository
    table: game_subject
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        doneColor:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: done_color
        todoColor:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: todo_color
    lifecycleCallbacks: {  }
