PacksAnSpielBundle\Entity\Game:
    type: entity
    table: game
    repositoryClass: PacksAnSpielBundle\Repository\GameRepository
    indexes:
        fk_game_game_subject1_idx:
            columns:
                - game_subject_id
        fk_game_level1_idx:
            columns:
                - level_id
        fk_game_location1_idx:
            columns:
                - location_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        passcode:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        duration:
            type: integer
            nullable: true
            options:
                unsigned: false
        status:
            type: boolean
            nullable: true
        game_description:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        group_text_game_start:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        group_text_game_question:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        group_text_game_correct_answer:
            type: text
            nullable: true
            length: 140
            options:
                fixed: false
        group_text_game_wrong_answer_1:
            type: text
            nullable: true
            length: 140
            options:
                fixed: false
        group_text_game_wrong_answer_2:
            type: text
            nullable: true
            length: 140
            options:
                fixed: false
        group_text_game_wrong_answer_3:
            type: text
            nullable: true
            length: 140
            options:
                fixed: false
        group_text_game_end:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
    manyToOne:
        gameSubject:
            targetEntity: GameSubject
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                game_subject_id:
                    referencedColumnName: id
            orphanRemoval: false
        level:
            targetEntity: Level
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                level_id:
                    referencedColumnName: id
            orphanRemoval: false
        location:
            targetEntity: Location
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                location_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        parentGame:
            targetEntity: Game
            joinColumn:
                name: parent_game
                referencedColumnName: id

    lifecycleCallbacks: {  }
