PacksAnSpielBundle\Entity\Joker:
    type: entity
    table: joker
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        jokercode:
            type: string
            nullable: true
            length: 32
            options:
                fixed: false
        jokerUsed:
            type: boolean
            nullable: true
            column: joker_used
        created:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
