PacksAnSpielBundle\Entity\Member:
    type: entity
    table: member
    indexes:
        fk_member_team1_idx:
            columns:
                - team_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        stufe:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        team:
            targetEntity: Team
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
