PacksAnSpielBundle\Entity\Member:
    type: entity
    repositoryClass: PacksAnSpielBundle\Repository\MemberRepository
    table: member
    indexes:
        fk_member_team1_idx:
            columns:
                - team_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        passcode:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        grade:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        team:
            targetEntity: Team
            inversedBy: team_members
            joinColumns:
                team_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
