PacksAnSpielBundle\Entity\Message:
    type: entity
    table: message
    indexes:
        fk_message_team1_idx:
            columns:
                - team_id
        fk_message_game1_idx:
            columns:
                - game_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        messageText:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: message_text
        sendTime:
            type: datetime
            nullable: true
            column: send_time
        readTime:
            type: datetime
            nullable: true
            column: read_time
    manyToOne:
        game:
            targetEntity: Game
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                game_id:
                    referencedColumnName: id
            orphanRemoval: false
        team:
            targetEntity: Team
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
