PacksAnSpielBundle\Entity\Team:
    type: entity
    repositoryClass: PacksAnSpielBundle\Repository\TeamRepository
    table: team
    indexes:
        fk_team_level1_idx:
            columns:
                - current_level
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        passcode:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        memberOfTeam:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: member_of_team
        countPersons:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: count_persons
        status:
            type: boolean
            nullable: true
    manyToOne:
        currentLevel:
            targetEntity: Level
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                current_level:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        teamMembers:
            targetEntity: Member
            mappedBy: team

    lifecycleCallbacks: {  }
