PacksAnSpielBundle\Entity\Team:
    type: entity
    repositoryClass: PacksAnSpielBundle\Repository\TeamRepository
    table: team
    indexes:
        fk_team_level1_idx:
            columns:
                - current_level
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        passcode:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        parentTeam:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: parent_team
        status:
            type: integer
            nullable: true
    manyToOne:
        currentLevel:
            targetEntity: Level
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                current_level:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        teamMembers:
            targetEntity: Member
            mappedBy: team
        logEntries:
            targetEntity: Actionlog
            mappedBy: team

    lifecycleCallbacks: {  }
