PacksAnSpielBundle\Entity\TeamLevelGame:
    type: entity
    table: team_level_game
    indexes:
        fk_team_level_game_team_level1_idx:
            columns:
                - team_level_id
        fk_team_level_game_game_subject1_idx:
            columns:
                - assigned_game_subject
        fk_team_level_game_joker1_idx:
            columns:
                - used_joker
        fk_team_level_game_game1_idx:
            columns:
                - assigned_game
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        playedPoints:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: played_points
        startTime:
            type: integer
            nullable: true
            length: 45
            options:
                fixed: false
            column: start_time
        finishTime:
            type: integer
            nullable: true
            length: 45
            options:
                fixed: false
            column: finish_time
        solvedByLeveljump:
            type: boolean
            nullable: true
            column: solved_by_leveljump
    manyToOne:
        assignedGame:
            targetEntity: Game
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assigned_game:
                    referencedColumnName: id
            orphanRemoval: false
        assignedGameSubject:
            targetEntity: GameSubject
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                assigned_game_subject:
                    referencedColumnName: id
            orphanRemoval: false
        teamLevel:
            targetEntity: TeamLevel
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                team_level_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        usedJoker:
            targetEntity: Joker
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                used_joker:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
