PacksAnSpielBundle\Entity\Terminal:
    type: entity
    table: terminal
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "\t\t\t"
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
